dataset<-read.delim(file="C:/Users/vig19/OneDrive/Desktop/R CourseEra/Exploratory Data Analysis/Week 1/household_power_consumption.txt",sep=";",header = TRUE,dec=".")
  subdataset <- subset(dataset,dataset$Date=="1/2/2007" | dataset$Date =="2/2/2007")
    subdataset$Date<-as.Date(subdataset$Date,format="%d/%m/%y")
    subdataset$Time<-strptime(subdataset$Time,format="%H:%M:%S")
    subdataset[1:1440,"Time"] <- format(subdataset[1:1440,"Time"],"2007-02-01 %H:%M:%S")
    subdataset[1441:2880,"Time"] <- format(subdataset[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
    png(filename = "C:/Users/vig19/OneDrive/Desktop/R CourseEra/Exploratory Data Analysis/Week 1/Power/Plot 2 - Global Active Power by Day.png",width = 600, height = 480)
      plot(subdataset$Time,as.numeric(subdataset$Global_active_power),type = "l",xlab="",ylab = "Global Active Power (kilowatts)")
      dev.off()